# Generated by Django 3.2.18 on 2023-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
