# Generated by Django 3.2.18 on 2023-05-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_comment',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
