# Generated by Django 3.2.18 on 2023-06-01 05:54

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20230526_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
