# Generated by Django 3.2.18 on 2023-05-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
