# Generated by Django 3.2.18 on 2023-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_rename_like_user_garden_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='ex_content',
            field=models.TextField(default='Default value'),
        ),
    ]
