# Generated by Django 3.2.18 on 2023-05-26 05:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230525_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user_title'),
        ),
    ]
