
# Generated by Django 3.2.18 on 2023-06-06 08:05


# Generated by Django 3.2.18 on 2023-06-07 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import managements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0002_alter_plant_tags'),

    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering', models.CharField(max_length=20)),
                ('sunlight', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),

                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.management')),

                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
