# Generated by Django 3.2.18 on 2023-06-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenderentry',
            name='category',
        ),
    ]
