# Generated by Django 3.2.18 on 2023-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderentry',
            name='entrydate',
            field=models.DateField(null=True),
        ),
    ]
