# Generated by Django 3.2.18 on 2023-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='managementdate',
            field=models.DateField(null=True),
        ),
    ]
