# Generated by Django 3.2.18 on 2023-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('pot', '화분'), ('fertilizer', '비료'), ('nutrition', '영양제'), ('decoration', '데코레이션'), ('sprinkler', '물뿌리개')], max_length=20)),
                ('like', models.PositiveIntegerField(default=0)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
