# Generated by Django 3.2.18 on 2023-05-24 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplies.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='product_name',
            new_name='content',
        ),
        migrations.AddField(
            model_name='supply',
            name='photo',
            field=models.ImageField(default=1, upload_to=supplies.models.supply_img_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='supply_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='supply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='supply',
            name='like',
        ),
        migrations.AddField(
            model_name='supply',
            name='like',
            field=models.ManyToManyField(related_name='like_supply', to=settings.AUTH_USER_MODEL),
        ),
    ]
