# Generated by Django 3.2.18 on 2023-05-25 06:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20230524_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
