# Generated by Django 3.2.18 on 2023-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
