# Generated by Django 3.2.18 on 2023-06-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
