# Generated by Django 3.2.18 on 2023-05-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='birthflower',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='meaning',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
