# Generated by Django 3.2.18 on 2023-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='flowering',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='season',
        ),
    ]
