# Generated by Django 3.2.18 on 2023-05-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20230524_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='title',
        ),
    ]
