# Generated by Django 3.2.18 on 2023-06-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='content',
            field=models.TextField(max_length=460),
        ),
    ]
