# Generated by Django 3.2.18 on 2023-05-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_rename_name_plant_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='users',
            new_name='user',
        ),
    ]
