# Generated by Django 3.2.18 on 2023-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='flowering',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='season',
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
