# Generated by Django 3.2.18 on 2023-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20230606_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='price',
        ),
        migrations.AddField(
            model_name='plant',
            name='flowering',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='season',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
