# Generated by Django 3.2.18 on 2023-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20230606_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='content',
            field=models.CharField(max_length=460),
        ),
    ]
