# Generated by Django 3.2.18 on 2023-06-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_content'),
        ('plants', '0006_auto_20230606_0118'),
    ]

    operations = [
    ]
