# Generated by Django 3.2.18 on 2023-06-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
