# Generated by Django 3.2.18 on 2023-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
